# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- citest

pool:
  name: 'DLTS-Platform'

# container: ubuntu:18.04

variables: { SUBSCRIPTION_NAME: "'Bing DLTS'"}

steps:

- script: |
    echo TODO: RUN functional tests!
  displayName: 'Functional tests'

